export { AppSidebar, DashboardHeader, DashboardPageWrapper } from '@/widgets/sidebar'
export type { DashboardBreadcrumb } from '@/widgets/sidebar/model/types'
export { PageHeader } from '@/widgets/page-header'
export type { PageHeaderProps } from '@/widgets/page-header/model/types'
export { Navigation } from '@/widgets/navigation'
export type { NavigationCategory, NavigationData, NavigationItem } from '@/widgets/navigation/model/types'
